appConfig: "weaver.toml"
listeners:
  - name: boutique
    public: true
    port: 8080
groups:
  - name: monolith
    components:
      - github.com/ServiceWeaver/onlineboutique/frontend/T
      - github.com/ServiceWeaver/onlineboutique/adservice/T
      - github.com/ServiceWeaver/onlineboutique/cartservice/T
      - github.com/ServiceWeaver/onlineboutique/cartservice/cartCache
      - github.com/ServiceWeaver/onlineboutique/checkoutservice/T
      - github.com/ServiceWeaver/onlineboutique/currencyservice/T
      - github.com/ServiceWeaver/onlineboutique/emailservice/T
      - github.com/ServiceWeaver/onlineboutique/paymentservice/T
      - github.com/ServiceWeaver/onlineboutique/productcatalogservice/T
      - github.com/ServiceWeaver/onlineboutique/recommendationservice/T
      - github.com/ServiceWeaver/onlineboutique/shippingservice/T
