appConfig: "weaver.toml"
listeners:
  - name: boutique
    public: true
    port: 8080
groups:
  - name: fe
    components:
      - github.com/ServiceWeaver/onlineboutique/frontend/weaver.Main
      - github.com/ServiceWeaver/onlineboutique/adservice/AdService
      - github.com/ServiceWeaver/onlineboutique/cartservice/CartService
      - github.com/ServiceWeaver/onlineboutique/checkoutservice/CheckoutService
      - github.com/ServiceWeaver/onlineboutique/currencyservice/CurrencyService
  - name: be
    components:
      - github.com/ServiceWeaver/onlineboutique/emailservice/EmailService
      - github.com/ServiceWeaver/onlineboutique/paymentservice/PaymentService
      - github.com/ServiceWeaver/onlineboutique/productcatalogservice/ProductCatalogService
      - github.com/ServiceWeaver/onlineboutique/recommendationservice/RecommendationService
      - github.com/ServiceWeaver/onlineboutique/shippingservice/ShippingService
