# =============================================================================
# CONFIG 1VM-A: Monolith
# All 11 components co-located in a single OS process.
# =============================================================================
[serviceweaver]
name   = "boutique-1vm-monolith"
binary = "../onlineboutique/boutique"

# All components in one group → single process (true monolith)
colocate = [
  [
    "github.com/ServiceWeaver/weaver/Main",
    "github.com/ServiceWeaver/onlineboutique/adservice/AdService",
    "github.com/ServiceWeaver/onlineboutique/cartservice/CartService",
    "github.com/ServiceWeaver/onlineboutique/checkoutservice/CheckoutService",
    "github.com/ServiceWeaver/onlineboutique/currencyservice/CurrencyService",
    "github.com/ServiceWeaver/onlineboutique/emailservice/EmailService",
    "github.com/ServiceWeaver/onlineboutique/paymentservice/PaymentService",
    "github.com/ServiceWeaver/onlineboutique/productcatalogservice/ProductCatalogService",
    "github.com/ServiceWeaver/onlineboutique/recommendationservice/RecommendationService",
    "github.com/ServiceWeaver/onlineboutique/shippingservice/ShippingService",
  ],
]

[multi]
listeners.boutique = {address = "localhost:8080"}

